/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'rights-documents': RightsDocument;
    'media-masters': MediaMaster;
    'media-assets': MediaAsset;
    sources: Source;
    people: Person;
    places: Place;
    artifacts: Artifact;
    themes: Theme;
    events: Event;
    'evidence-claims': EvidenceClaim;
    'evidence-links': EvidenceLink;
    'journey-acts': JourneyAct;
    scenes: Scene;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'evidence-claims': {
      sourceLinks: 'evidence-links';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'rights-documents': RightsDocumentsSelect<false> | RightsDocumentsSelect<true>;
    'media-masters': MediaMastersSelect<false> | MediaMastersSelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    artifacts: ArtifactsSelect<false> | ArtifactsSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'evidence-claims': EvidenceClaimsSelect<false> | EvidenceClaimsSelect<true>;
    'evidence-links': EvidenceLinksSelect<false> | EvidenceLinksSelect<true>;
    'journey-acts': JourneyActsSelect<false> | JourneyActsSelect<true>;
    scenes: ScenesSelect<false> | ScenesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en') | ('id' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'id' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName: string;
  role: 'admin' | 'publisher' | 'historical_reviewer' | 'editor' | 'researcher' | 'asset_curator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Private. Never public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rights-documents".
 */
export interface RightsDocument {
  id: number;
  title: string;
  rightsType:
    | 'institutional_permission'
    | 'licence_agreement'
    | 'subject_release'
    | 'community_donation'
    | 'public_domain_assessment';
  institution?: string | null;
  effectiveFrom?: string | null;
  expiresAt?: string | null;
  /**
   * Scope and limits of the permission, in plain language.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Private archival masters. Never public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-masters".
 */
export interface MediaMaster {
  id: number;
  title: string;
  originInstitution: string;
  /**
   * Catalogue or shelfmark reference at the holding institution.
   */
  inventoryReference?: string | null;
  sourceUrl?: string | null;
  /**
   * SHA-256 of the original file as received.
   */
  checksum?: string | null;
  /**
   * The permission this master was received under.
   */
  rightsDocument?: (number | null) | RightsDocument;
  /**
   * Once approved, provenance fields become immutable.
   */
  approved?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: number;
  title: string;
  /**
   * Describe what is visible, for someone who cannot see it. Required before publishing.
   */
  altText?: string | null;
  /**
   * Public caption: what it shows, when, and where.
   */
  caption?: string | null;
  visualEvidenceClass?:
    | (
        | 'V0_primary_object'
        | 'V1_documentary_historical_image'
        | 'V2_verified_contemporary_documentation'
        | 'V3_evidence_constrained_reconstruction'
        | 'V4_artistic_interpretation'
        | 'V5_folklore_visualization'
      )
    | null;
  rightsClass?:
    | (
        | 'R0_public_domain'
        | 'R1_open_license'
        | 'R2_institutional_use'
        | 'R3_permission_required'
        | 'R4_editorial_commercial_license'
        | 'R5_reference_only'
      )
    | null;
  /**
   * The private archival original this derivative comes from.
   */
  master?: (number | null) | MediaMaster;
  rightsDocument?: (number | null) | RightsDocument;
  rightsExpiresAt?: string | null;
  creator?: string | null;
  institution?: string | null;
  /**
   * Exactly as the holding institution requires it to appear.
   */
  creditLine?: string | null;
  /**
   * When the image was made.
   */
  dateCreated?: string | null;
  /**
   * When the subject existed.
   */
  dateDepicted?: string | null;
  /**
   * Archival captions carry the politics of the archive that wrote them. Record that context here rather than repeating it as narration.
   */
  contextNote?: string | null;
  /**
   * What this image does NOT establish.
   */
  uncertaintyNote?: string | null;
  assetStatus?: ('green' | 'blue' | 'amber' | 'red' | 'black') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  sourceType:
    | 'inscription'
    | 'manuscript'
    | 'archival_document'
    | 'law'
    | 'government_record'
    | 'official_statistics'
    | 'museum_catalogue'
    | 'photograph'
    | 'map'
    | 'academic_book'
    | 'academic_article'
    | 'thesis'
    | 'newspaper'
    | 'oral_history'
    | 'corporate_record'
    | 'community_archive'
    | 'website';
  authors?: string[] | null;
  institution?: string | null;
  publisher?: string | null;
  publicationYear?: number | null;
  language?: string | null;
  reliabilityTier?:
    ('primary' | 'peer_reviewed' | 'institutional' | 'reputable_secondary' | 'popular' | 'unverified') | null;
  archiveCollection?: string | null;
  inventoryNumber?: string | null;
  url?: string | null;
  doi?: string | null;
  isbn?: string | null;
  /**
   * Full citation as it should appear publicly.
   */
  citation?: string | null;
  accessDate?: string | null;
  linkStatus?: ('active' | 'superseded' | 'withdrawn' | 'broken_link') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  canonicalName: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  displayName?: string | null;
  /**
   * Historical spellings and alternative names. Searchable, and shown where naming matters.
   */
  aliases?: string[] | null;
  titles?: string[] | null;
  regnalNames?: string[] | null;
  birthChronology?: {
    /**
     * Negative for BCE.
     */
    startYear?: number | null;
    startMonth?: number | null;
    startDay?: number | null;
    endYear?: number | null;
    endMonth?: number | null;
    endDay?: number | null;
    /**
     * Pick the precision the evidence actually supports. Never widen a date to fit a field.
     */
    precision?: ('exact_day' | 'month' | 'year' | 'range' | 'decade' | 'century' | 'approximate') | null;
    /**
     * Human-readable form shown to the public, e.g. "27 Juli 879" or "c. 1042".
     */
    display?: string | null;
  };
  deathChronology?: {
    /**
     * Negative for BCE.
     */
    startYear?: number | null;
    startMonth?: number | null;
    startDay?: number | null;
    endYear?: number | null;
    endMonth?: number | null;
    endDay?: number | null;
    /**
     * Pick the precision the evidence actually supports. Never widen a date to fit a field.
     */
    precision?: ('exact_day' | 'month' | 'year' | 'range' | 'decade' | 'century' | 'approximate') | null;
    /**
     * Human-readable form shown to the public, e.g. "27 Juli 879" or "c. 1042".
     */
    display?: string | null;
  };
  /**
   * What kind of image may ever stand for this person. Default assumes no authenticated likeness exists.
   */
  representationPolicy:
    'authenticated_likeness' | 'historical_photograph' | 'period_portrait' | 'symbolic_only' | 'no_known_likeness';
  summary?: string | null;
  biography?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  canonicalName: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  aliases?: string[] | null;
  placeType:
    | 'city'
    | 'region'
    | 'river'
    | 'kingdom'
    | 'settlement'
    | 'archaeological_site'
    | 'building'
    | 'bridge'
    | 'religious_site'
    | 'industrial_site'
    | 'transport_site'
    | 'landscape'
    | 'uncertain_historical_location';
  /**
   * Only for places that genuinely survive at a known location today.
   */
  modernLocation?: {
    latitude?: number | null;
    longitude?: number | null;
    addressContext?: string | null;
  };
  /**
   * Where scholarship places it, and how confidently. Never sharpen a zone into a border.
   */
  historicalLocation?: {
    certainty?: ('precise' | 'approximate_zone' | 'disputed' | 'unknown') | null;
    description?: string | null;
    /**
     * Reference to a reconstruction dataset, never a fabricated exact polygon.
     */
    geometryReference?: string | null;
  };
  administrativeContext?: string | null;
  heritageStatus?: string | null;
  summary?: string | null;
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts".
 */
export interface Artifact {
  id: number;
  canonicalName: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  aliases?: string[] | null;
  artifactType:
    | 'inscription'
    | 'manuscript'
    | 'sculpture'
    | 'architectural_element'
    | 'coin'
    | 'ceramic'
    | 'tool'
    | 'machine'
    | 'document'
    | 'photograph_object'
    | 'textile'
    | 'other';
  chronology?: {
    /**
     * Negative for BCE.
     */
    startYear?: number | null;
    startMonth?: number | null;
    startDay?: number | null;
    endYear?: number | null;
    endMonth?: number | null;
    endDay?: number | null;
    /**
     * Pick the precision the evidence actually supports. Never widen a date to fit a field.
     */
    precision?: ('exact_day' | 'month' | 'year' | 'range' | 'decade' | 'century' | 'approximate') | null;
    /**
     * Human-readable form shown to the public, e.g. "27 Juli 879" or "c. 1042".
     */
    display?: string | null;
  };
  material?: string | null;
  dimensions?: string | null;
  holdingInstitution?: string | null;
  /**
   * Catalogue reference, e.g. D.9 at Museum Nasional.
   */
  inventoryNumber?: string | null;
  /**
   * The documented findspot. Never stage an object as if it were excavated where the story is set.
   */
  discoveryLocation?: (number | null) | Place;
  currentLocation?: (number | null) | Place;
  provenance?: string | null;
  transcription?: string | null;
  translation?: string | null;
  media?: (number | MediaAsset)[] | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  title: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order: number;
  heroMedia?: (number | null) | MediaAsset;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  canonicalName: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  aliases?: string[] | null;
  chronology: {
    /**
     * Negative for BCE.
     */
    startYear: number;
    startMonth?: number | null;
    startDay?: number | null;
    endYear?: number | null;
    endMonth?: number | null;
    endDay?: number | null;
    /**
     * Pick the precision the evidence actually supports. Never widen a date to fit a field.
     */
    precision: 'exact_day' | 'month' | 'year' | 'range' | 'decade' | 'century' | 'approximate';
    /**
     * Human-readable form shown to the public, e.g. "27 Juli 879" or "c. 1042".
     */
    display: string;
  };
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  people?: (number | Person)[] | null;
  places?: (number | Place)[] | null;
  artifacts?: (number | Artifact)[] | null;
  themes?: (number | Theme)[] | null;
  /**
   * The atomic propositions this event rests on. Public factual copy must be traceable to one of these.
   */
  claims?: (number | EvidenceClaim)[] | null;
  relatedEvents?: (number | Event)[] | null;
  reviewStatus: 'researching' | 'needs_review' | 'reviewed' | 'approved';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-claims".
 */
export interface EvidenceClaim {
  id: number;
  /**
   * One atomic proposition, stated precisely. Split anything that needs the word and.
   */
  canonicalStatement: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  /**
   * How this is phrased for the public.
   */
  publicSummary?: string | null;
  evidenceClass:
    | 'primary_record'
    | 'historical_fact'
    | 'scholarly_interpretation'
    | 'tradition'
    | 'folklore'
    | 'modern_verified_data';
  /**
   * How strongly this is attested. Independent of the evidence class.
   */
  confidence: 'high' | 'moderate' | 'low' | 'contested';
  /**
   * Every link from this claim to a source, with its role and strength.
   */
  sourceLinks?: {
    docs?: (number | EvidenceLink)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  events?: (number | Event)[] | null;
  people?: (number | Person)[] | null;
  places?: (number | Place)[] | null;
  artifacts?: (number | Artifact)[] | null;
  /**
   * Where scholarship disagrees, record the disagreement. Never reconcile it silently.
   */
  competingClaims?: (number | EvidenceClaim)[] | null;
  /**
   * Corrections replace, they do not overwrite.
   */
  supersededBy?: (number | null) | EvidenceClaim;
  /**
   * Internal. Never rendered publicly.
   */
  editorialNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-links".
 */
export interface EvidenceLink {
  id: number;
  claim: number | EvidenceClaim;
  source: number | Source;
  role: 'supports' | 'contradicts' | 'contextualizes' | 'mentions';
  strength: 'direct' | 'strong' | 'moderate' | 'weak';
  /**
   * Page, chapter, inscription line, archive frame, table, or paragraph. Be exact.
   */
  locator?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-acts".
 */
export interface JourneyAct {
  id: number;
  order: number;
  title: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  subtitle?: string | null;
  /**
   * Shown to the reader, e.g. 879 - 1042.
   */
  dateRangeDisplay: string;
  introCopy?: string | null;
  /**
   * Which code-defined era palette applies. The CMS selects intent, not colour values.
   */
  visualEraKey:
    | 'present'
    | 'ancient'
    | 'panjalu'
    | 'collapse'
    | 'memory'
    | 'seventeenthCentury'
    | 'colonialIndustrial'
    | 'occupationRevolution'
    | 'industrialCity'
    | 'connectedModern'
    | 'finale';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenes".
 */
export interface Scene {
  id: number;
  order: number;
  act: number | JourneyAct;
  title: string;
  /**
   * Stable public identifier. Changing it breaks shared links.
   */
  slug: string;
  subtitle?: string | null;
  /**
   * The date as the reader sees it, e.g. 1135.
   */
  dateDisplay: string;
  /**
   * The single event this scene presents. Historical facts come from here, never from scene copy.
   */
  primaryEvent?: (number | null) | Event;
  supportingEvents?: (number | Event)[] | null;
  /**
   * Depth 1: the glance. One statement.
   */
  narrativeShort?: string | null;
  /**
   * Depth 2: the story. Context and interpretation.
   */
  narrativeLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Satu kalimat yang memikul scene ini, disajikan dalam tipografi monumental. Naskah editorial adalah milik CMS (Technical Bible bagian 19); kode hanya memiliki tipografinya. Ia harus tetap terbaca pada keadaan istirahat, bukan hanya pada satu titik progres gulir (UX Bible bagian 39).
   */
  masterLine?: string | null;
  /**
   * Only published claims may appear here. Depth 3 opens from these.
   */
  featuredClaims?: (number | EvidenceClaim)[] | null;
  featuredPeople?: (number | Person)[] | null;
  featuredPlaces?: (number | Place)[] | null;
  featuredArtifacts?: (number | Artifact)[] | null;
  themes?: (number | Theme)[] | null;
  /**
   * One dominant visual idea. If reviewers cannot name it, the scene is unfocused.
   */
  heroMedia?: (number | null) | MediaAsset;
  featuredMedia?: (number | MediaAsset)[] | null;
  /**
   * auto derives the badge from the featured claims. Force a mode only where a scene deliberately shifts register, such as history beside tradition.
   */
  evidenceBadgeMode: 'auto' | 'always' | 'hidden';
  /**
   * Intent only, sama seperti choreographyKey: ia memilih perlakuan visual yang sudah teruji di kode, bukan menyimpan nilai gaya.
   */
  visualVariant?: ('material' | 'landscape' | 'word' | 'structure' | 'document') | null;
  /**
   * Intent only. The code registry maps this to a tested timeline.
   */
  choreographyKey?:
    | (
        | 'prologueReveal'
        | 'inscriptionReveal'
        | 'nameEmerges'
        | 'nameEndures'
        | 'dividedKingdom'
        | 'royalConsolidation'
        | 'manuscriptWorld'
        | 'politicalFracture'
        | 'bridgeConstruction'
        | 'bridgeLift'
        | 'revolutionMachine'
        | 'industrialExpansion'
        | 'runwayTransition'
      )
    | null;
  sceneType: 'hero' | 'supporting' | 'interlude' | 'optional';
  seo?: {
    title?: string | null;
    description?: string | null;
    shareMedia?: (number | null) | MediaAsset;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'rights-documents';
        value: number | RightsDocument;
      } | null)
    | ({
        relationTo: 'media-masters';
        value: number | MediaMaster;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: number | MediaAsset;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'artifacts';
        value: number | Artifact;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'evidence-claims';
        value: number | EvidenceClaim;
      } | null)
    | ({
        relationTo: 'evidence-links';
        value: number | EvidenceLink;
      } | null)
    | ({
        relationTo: 'journey-acts';
        value: number | JourneyAct;
      } | null)
    | ({
        relationTo: 'scenes';
        value: number | Scene;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rights-documents_select".
 */
export interface RightsDocumentsSelect<T extends boolean = true> {
  title?: T;
  rightsType?: T;
  institution?: T;
  effectiveFrom?: T;
  expiresAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-masters_select".
 */
export interface MediaMastersSelect<T extends boolean = true> {
  title?: T;
  originInstitution?: T;
  inventoryReference?: T;
  sourceUrl?: T;
  checksum?: T;
  rightsDocument?: T;
  approved?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  title?: T;
  altText?: T;
  caption?: T;
  visualEvidenceClass?: T;
  rightsClass?: T;
  master?: T;
  rightsDocument?: T;
  rightsExpiresAt?: T;
  creator?: T;
  institution?: T;
  creditLine?: T;
  dateCreated?: T;
  dateDepicted?: T;
  contextNote?: T;
  uncertaintyNote?: T;
  assetStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  sourceType?: T;
  authors?: T;
  institution?: T;
  publisher?: T;
  publicationYear?: T;
  language?: T;
  reliabilityTier?: T;
  archiveCollection?: T;
  inventoryNumber?: T;
  url?: T;
  doi?: T;
  isbn?: T;
  citation?: T;
  accessDate?: T;
  linkStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  canonicalName?: T;
  slug?: T;
  displayName?: T;
  aliases?: T;
  titles?: T;
  regnalNames?: T;
  birthChronology?:
    | T
    | {
        startYear?: T;
        startMonth?: T;
        startDay?: T;
        endYear?: T;
        endMonth?: T;
        endDay?: T;
        precision?: T;
        display?: T;
      };
  deathChronology?:
    | T
    | {
        startYear?: T;
        startMonth?: T;
        startDay?: T;
        endYear?: T;
        endMonth?: T;
        endDay?: T;
        precision?: T;
        display?: T;
      };
  representationPolicy?: T;
  summary?: T;
  biography?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  canonicalName?: T;
  slug?: T;
  aliases?: T;
  placeType?: T;
  modernLocation?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        addressContext?: T;
      };
  historicalLocation?:
    | T
    | {
        certainty?: T;
        description?: T;
        geometryReference?: T;
      };
  administrativeContext?: T;
  heritageStatus?: T;
  summary?: T;
  history?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts_select".
 */
export interface ArtifactsSelect<T extends boolean = true> {
  canonicalName?: T;
  slug?: T;
  aliases?: T;
  artifactType?: T;
  chronology?:
    | T
    | {
        startYear?: T;
        startMonth?: T;
        startDay?: T;
        endYear?: T;
        endMonth?: T;
        endDay?: T;
        precision?: T;
        display?: T;
      };
  material?: T;
  dimensions?: T;
  holdingInstitution?: T;
  inventoryNumber?: T;
  discoveryLocation?: T;
  currentLocation?: T;
  provenance?: T;
  transcription?: T;
  translation?: T;
  media?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  order?: T;
  heroMedia?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  canonicalName?: T;
  slug?: T;
  aliases?: T;
  chronology?:
    | T
    | {
        startYear?: T;
        startMonth?: T;
        startDay?: T;
        endYear?: T;
        endMonth?: T;
        endDay?: T;
        precision?: T;
        display?: T;
      };
  summary?: T;
  description?: T;
  people?: T;
  places?: T;
  artifacts?: T;
  themes?: T;
  claims?: T;
  relatedEvents?: T;
  reviewStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-claims_select".
 */
export interface EvidenceClaimsSelect<T extends boolean = true> {
  canonicalStatement?: T;
  slug?: T;
  publicSummary?: T;
  evidenceClass?: T;
  confidence?: T;
  sourceLinks?: T;
  events?: T;
  people?: T;
  places?: T;
  artifacts?: T;
  competingClaims?: T;
  supersededBy?: T;
  editorialNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-links_select".
 */
export interface EvidenceLinksSelect<T extends boolean = true> {
  claim?: T;
  source?: T;
  role?: T;
  strength?: T;
  locator?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-acts_select".
 */
export interface JourneyActsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  dateRangeDisplay?: T;
  introCopy?: T;
  visualEraKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenes_select".
 */
export interface ScenesSelect<T extends boolean = true> {
  order?: T;
  act?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  dateDisplay?: T;
  primaryEvent?: T;
  supportingEvents?: T;
  narrativeShort?: T;
  narrativeLong?: T;
  masterLine?: T;
  featuredClaims?: T;
  featuredPeople?: T;
  featuredPlaces?: T;
  featuredArtifacts?: T;
  themes?: T;
  heroMedia?: T;
  featuredMedia?: T;
  evidenceBadgeMode?: T;
  visualVariant?: T;
  choreographyKey?: T;
  sceneType?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        shareMedia?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}