"use client";

import { useState } from "react";
import { defaultReviewItems, freshReview, type ReviewItem } from "../lib/workflow";
import { newId, type Message, type WorkspaceAction } from "../lib/workspace";
import { documentSections } from "../lib/studio";

export function HistoryPanel({ message, encounterId, dispatch }: { message: Message; encounterId: string; dispatch: (action: WorkspaceAction) => void }) {
  const [selected, setSelected] = useState<string | null>(null);
  const [name, setName] = useState("");
  const [confirm, setConfirm] = useState(false);
  const versions = message.revisions ?? [];
  const revision = versions.find((item) => item.id === selected);
  return <div className="history-panel"><p className="panel-caption">Isi sebelum perubahan disimpan hingga 50 versi. Versi tertua setelah batas ini akan dilepas; draf awal tetap tersedia di Perubahan. Riwayat lokal bukan audit permanen.</p>{!versions.length && <p className="panel-empty">Belum ada versi tersimpan. Riwayat dimulai pada perubahan berikutnya.</p>}<div className="history-versions">{[...versions].reverse().map((item) => <button className="button" key={item.id} aria-pressed={selected === item.id} onClick={() => { setSelected(item.id); setName(item.name); setConfirm(false); }}>{item.name || (item.reason === "restore" ? "Sebelum pemulihan" : "Sebelum edit")} · {new Date(item.savedAt).toLocaleString("id-ID", { timeZone: "Asia/Jakarta" })} WIB</button>)}</div>{revision && <><form className="workflow-actions" onSubmit={(event) => { event.preventDefault(); dispatch({ type: "revision.rename", encounterId, messageId: message.id, id: revision.id, name: name.trim() }); }}><input aria-label="Nama versi" value={name} maxLength={80} onChange={(event) => setName(event.target.value)} placeholder="Nama versi…"/><button className="button">Simpan nama versi</button></form><div className="studio-columns comparison"><div><h3>Versi dipilih</h3><pre>{revision.content}</pre></div><div><h3>Saat ini</h3><pre>{message.content}</pre></div></div><button className="button" disabled={message.content === revision.content} onClick={() => setConfirm(true)}>Pulihkan versi</button>{confirm && <div className="form-warning"><p>Isi saat ini akan disimpan sebagai versi sebelum pemulihan. Status kembali Draf dan checklist harus ditinjau ulang.</p><button className="button primary" onClick={() => { dispatch({ type: "revision.restore", encounterId, messageId: message.id, id: revision.id, at: new Date().toISOString() }); setConfirm(false); }}>Konfirmasi pemulihan</button><button className="button" onClick={() => setConfirm(false)}>Batal</button></div>}</>}</div>;
}
export function ReviewPanel({ message, encounterId, dispatch, onNavigate }: { message: Message; encounterId: string; dispatch: (action: WorkspaceAction) => void; onNavigate: (target: string) => void }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<ReviewItem[]>([]);
  const [label, setLabel] = useState("");
  const items = message.reviewItems ?? freshReview(defaultReviewItems);
  const ref = { encounterId, messageId: message.id };
  return <div className="review-panel"><p className="panel-caption">Tanda peninjauan pengguna untuk isi saat ini. Ini bukan validasi klinis. Edit atau pemulihan mengosongkan tanda.</p>{items.map((item) => <div className="review-item" key={item.id}><label><input type="checkbox" checked={item.checked} onChange={() => dispatch({ type: "review.toggle", ...ref, id: item.id })}/>{item.label}{item.required && <small>Wajib</small>}</label><button className="text-button" onClick={() => onNavigate(item.target)}>Lihat bagian</button></div>)}<button className="button" onClick={() => { setDraft(items.map((item) => ({ ...item }))); setEditing(true); }}>Atur checklist dokumen</button>{editing && <div className="workflow-form">{draft.map((item) => <div key={item.id} className="review-edit-item"><input aria-label={`Label item ${item.id}`} value={item.label} maxLength={160} onChange={(event) => setDraft(draft.map((entry) => entry.id === item.id ? { ...entry, label: event.target.value } : entry))}/><label><input type="checkbox" checked={item.required} onChange={(event) => setDraft(draft.map((entry) => entry.id === item.id ? { ...entry, required: event.target.checked } : entry))}/>Wajib</label><select aria-label={`Target item ${item.id}`} value={item.target} onChange={(event) => setDraft(draft.map((entry) => entry.id === item.id ? { ...entry, target: event.target.value } : entry))}><option value="document">Dokumen</option><option value="source">Sumber</option>{documentSections(message.content).map((section) => <option key={section.start} value={section.title}>{section.title}</option>)}</select><button className="text-button" onClick={() => setDraft(draft.filter((entry) => entry.id !== item.id))}>Hapus item</button></div>)}<label>Item tambahan<input aria-label="Item peninjauan baru" maxLength={160} value={label} onChange={(event) => setLabel(event.target.value)}/></label><button className="button" disabled={!label.trim() || draft.length >= 30} onClick={() => { setDraft([...draft, { id: newId(), label: label.trim(), required: true, checked: false, target: "document" }]); setLabel(""); }}>Tambah item</button><p className="panel-caption">Minimal satu item wajib. Mengubah daftar membatalkan status dan seluruh tanda peninjauan.</p><div className="workflow-actions"><button className="button primary" disabled={!draft.some((item) => item.required) || draft.some((item) => !item.label.trim())} onClick={() => { dispatch({ type: "review.save", ...ref, items: draft }); setEditing(false); }}>Simpan checklist dokumen</button><button className="button" onClick={() => setEditing(false)}>Batal</button></div></div>}</div>;
}
