export const RME_STATISTIC_PAGES = {
  pendaftaran: {
    route: '/pendaftaran',
    containerSelector: 'table:nth-of-type(1)',
    rowSelector: 'tbody tr',
    paginationSelector: 'ul.pagination',
    columns: {
      tanggalPendaftaran: 'td:nth-child(3)',
      noPendaftaran: 'td:nth-child(4)',
      dataPasien: 'td:nth-child(5)',
      penyakitKhusus: 'td:nth-child(6)',
      ruanganDaftar: 'td:nth-child(7)',
      dokter: 'td:nth-child(8)',
      asuransi: 'td:nth-child(9)',
      statusPembayaran: 'td:nth-child(10)',
      statusBpjs: 'td:nth-child(11)',
      kunjungan: 'td:nth-child(12)',
      statusPelayanan: 'td:nth-child(13)',
    },
  },
  rujukanexternal: {
    route: '/rujukanexternal',
    containerSelector: 'table:nth-of-type(1)',
    rowSelector: 'tbody tr',
    paginationSelector: 'ul.pagination',
    columns: {
      tanggal: 'td:nth-child(2)',
      tenagaMedis1: 'td:nth-child(3)',
      tenagaMedis2: 'td:nth-child(4)',
      namaPasien: 'td:nth-child(7)',
      umur: 'td:nth-child(10)',
      rsTujuanRujukan: 'td:nth-child(11)',
      poliRuangan: 'td:nth-child(12)',
    },
  },
  stokobat: {
    route: '/stokobat',
    containerSelector: 'table:nth-of-type(1)',
    rowSelector: 'tbody tr',
    paginationSelector: 'ul.pagination',
    columns: {
      namaObat: 'td:nth-child(4)',
      jumlahStok: 'td:nth-child(5)',
      nilaiPersediaan: 'td:nth-child(13)',
      tanggalKadaluarsa: 'td:nth-child(15)',
      ruangan: 'td:nth-child(17)',
    },
  },
} as const;
