/**
 * Shared symptom alias map — colloquial Indonesian → clinical terms.
 * Used by both autocomplete (exact lookup) and pre-filter (query expansion).
 */

export const SYMPTOM_ALIASES: Record<string, string> = {
  panas: 'demam',
  'demam panas': 'demam',
  'panas tinggi': 'demam',
  'panas badan': 'demam',
  'panas dingin': 'demam',
  meriang: 'demam',
  'menggigil demam': 'demam',
  flu: 'pilek',
  'hidung meler': 'pilek',
  'hidung tersumbat': 'pilek',
  ingus: 'pilek',
  'kepala pusing': 'sakit kepala',
  pusing: 'sakit kepala',
  'pusing kepala': 'sakit kepala',
  migrain: 'sakit kepala',
  'sakit kepala belakang': 'sakit kepala',
  'tenggorokan sakit': 'nyeri tenggorokan',
  'radang tenggorokan': 'nyeri tenggorokan',
  'sakit telan': 'nyeri tenggorokan',
  'napas sesak': 'sesak napas',
  'susah napas': 'sesak napas',
  'napas pendek': 'sesak napas',
  'mual mual': 'mual',
  eneg: 'mual',
  'perut mual': 'mual',
  'muntah muntah': 'muntah',
  'mual muntah': 'mual',
  'bab cair': 'diare',
  mencret: 'diare',
  'diare cair': 'diare',
  'perut sakit': 'nyeri perut',
  'sakit perut': 'nyeri perut',
  'kram perut': 'nyeri perut',
  mules: 'nyeri perut',
  'dada sakit': 'nyeri dada',
  'sakit dada': 'nyeri dada',
  'nyeri kepala': 'sakit kepala',
  vertigo: 'pusing / vertigo',
  'kepala berputar': 'pusing / vertigo',
  lemas: 'lemas / fatigue',
  capek: 'lemas / fatigue',
  lelah: 'lemas / fatigue',
  lemah: 'lemas / fatigue',
  fatigue: 'lemas / fatigue',
  'punggung sakit': 'nyeri punggung',
  'sakit punggung': 'nyeri punggung',
  'pinggang sakit': 'nyeri pinggang',
  'sakit pinggang': 'nyeri pinggang',
  'nyeri pinggang': 'nyeri pinggang',
  'pinggang nyeri': 'nyeri pinggang',
  'sendi sakit': 'nyeri sendi',
  'sakit sendi': 'nyeri sendi',
  'nyeri persendian': 'nyeri sendi',
  'persendian nyeri': 'nyeri sendi',
  'persendian sakit': 'nyeri sendi',
  'sakit persendian': 'nyeri sendi',
  'nyeri di persendian': 'nyeri sendi',
  artralgia: 'nyeri sendi',
  arthralgia: 'nyeri sendi',
  'radang sendi': 'nyeri sendi',
  artritis: 'nyeri sendi',
  arthritis: 'nyeri sendi',
  gatal: 'gatal kulit',
  'gatal-gatal': 'gatal kulit',
  'kulit gatal': 'gatal kulit',
  ruam: 'ruam kulit',
  'bintik merah': 'ruam kulit',
  bentol: 'ruam kulit',
  'kaki bengkak': 'bengkak kaki',
  bengkak: 'bengkak kaki',
  'susah kencing': 'sulit bak',
  'susah bak': 'sulit bak',
  'kencing sakit': 'nyeri bak',
  'sakit kencing': 'nyeri bak',
  keputihan: 'keputihan',
  'haid sakit': 'nyeri haid',
  'mens sakit': 'nyeri haid',
  'jantung berdebar': 'berdebar-debar',
  berdebar: 'berdebar-debar',
  pingsan: 'pingsan / sinkop',
  sinkop: 'pingsan / sinkop',
  kesemutan: 'kebas / kesemutan',
  kebas: 'kebas / kesemutan',
  'mati rasa': 'kebas / kesemutan',
  'lemah anggota gerak': 'kelemahan anggota gerak',
  lumpuh: 'kelemahan anggota gerak',
  'penglihatan buram': 'penglihatan kabur',
  'mata buram': 'penglihatan kabur',
  kabur: 'penglihatan kabur',
  'mata merah': 'mata merah',
  'telinga berdenging': 'telinga berdenging',
  tinnitus: 'telinga berdenging',
  'pendengaran turun': 'gangguan pendengaran',
  'kurang dengar': 'gangguan pendengaran',
  mimisan: 'mimisan',
  'hidung berdarah': 'mimisan',
  'susah menelan': 'sulit menelan',
  'sakit menelan': 'sulit menelan',
  'tidak nafsu makan': 'nafsu makan menurun',
  'tidak mau makan': 'nafsu makan menurun',
  'berat badan turun': 'penurunan berat badan',
  'bb turun': 'penurunan berat badan',
  kurus: 'penurunan berat badan',
  'sering minum': 'banyak minum',
  polidipsia: 'banyak minum',
  'sering kencing': 'banyak kencing',
  poliuria: 'banyak kencing',
  'ulu hati': 'nyeri ulu hati',
  lambung: 'nyeri ulu hati',
  maag: 'nyeri ulu hati',
  kembung: 'kembung',
  'perut kembung': 'kembung',
  constipasi: 'sembelit',
  'susah bab': 'sembelit',
  'bab darah': 'bab berdarah',
  'darah di bab': 'bab berdarah',
  'bab hitam': 'bab hitam',
  'feses hitam': 'bab hitam',
  'wajah bengkak': 'bengkak wajah',
  'muka bengkak': 'bengkak wajah',
  'sesak tiduran': 'sesak saat berbaring',
  'sesak baring': 'sesak saat berbaring',
  'batuk berdarah': 'batuk darah',
  'darah batuk': 'batuk darah',
  'betis sakit': 'nyeri betis',
  'sakit betis': 'nyeri betis',
  kuning: 'kuning / ikterus',
  ikterus: 'kuning / ikterus',
  'mata kuning': 'kuning / ikterus',
  pegal: 'pegal linu',
  'badan pegal': 'pegal linu',
  'otot pegal': 'pegal linu',
  myalgia: 'pegal linu',
  'badan remuk': 'pegal linu',
  'sakit gigi': 'sakit gigi',
  'gigi sakit': 'sakit gigi',
  'gigi berlubang': 'sakit gigi',
  'gigi ngilu': 'sakit gigi',
  odontalgia: 'sakit gigi',
  'tengkuk kaku': 'tengkuk berat',
  'tengkuk pegal': 'tengkuk berat',
  'leher belakang kaku': 'tengkuk berat',
  'leher kaku': 'tengkuk berat',
  'luka tidak sembuh': 'luka sulit sembuh',
  'luka lama': 'luka sulit sembuh',
  'luka kronik': 'luka sulit sembuh',
  'ulkus kaki': 'luka sulit sembuh',
  'mata gatal': 'mata gatal berair',
  'mata berair': 'mata gatal berair',
  'mata perih': 'mata gatal berair',
  'mata bengkak gatal': 'mata gatal berair',
  'kuping sakit': 'nyeri telinga',
  'telinga sakit': 'nyeri telinga',
  otalgia: 'nyeri telinga',
  'sakit telinga': 'nyeri telinga',
  polifagia: 'sering lapar',
  'lapar terus': 'sering lapar',
  'nafsu makan berlebih': 'sering lapar',
  'keringat dingin': 'keringat dingin',
  'berkeringat dingin': 'keringat dingin',
  diaforesis: 'keringat dingin',
  insomnia: 'sulit tidur',
  'susah tidur': 'sulit tidur',
  'tidak bisa tidur': 'sulit tidur',
  'tidur tidak nyenyak': 'sulit tidur',
  'gusi bengkak': 'gusi bengkak',
  'gusi berdarah': 'gusi bengkak',
  gingivitis: 'gusi bengkak',
  'gusi merah': 'gusi bengkak',
  'bau mulut': 'bau mulut',
  halitosis: 'bau mulut',
  'napas bau': 'bau mulut',
  'mulut bau': 'bau mulut',
  sariawan: 'sariawan',
  stomatitis: 'sariawan',
  'luka mulut': 'sariawan',
  'sariawan mulut': 'sariawan',
  ketombe: 'ketombe',
  'kulit kepala gatal': 'ketombe',
  'serpihan putih': 'ketombe',
  seboroik: 'ketombe',
  'telinga berair': 'telinga keluar cairan',
  'kuping meler': 'telinga keluar cairan',
  otorrhea: 'telinga keluar cairan',
  'telinga berbau': 'telinga keluar cairan',
  serak: 'suara serak',
  'suara hilang': 'suara serak',
  parau: 'suara serak',
  disfonia: 'suara serak',
  'sendi kaku': 'sendi kaku pagi',
  'kaku pagi': 'sendi kaku pagi',
  'morning stiffness': 'sendi kaku pagi',
  'sendi bengkak': 'sendi bengkak merah',
  'sendi merah': 'sendi bengkak merah',
  'asam urat': 'sendi bengkak merah',
  gout: 'sendi bengkak merah',
  'jempol kaki bengkak': 'sendi bengkak merah',
  'tumit sakit': 'nyeri tumit',
  'sakit tumit': 'nyeri tumit',
  'plantar fasciitis': 'nyeri tumit',
  'nyeri telapak kaki': 'nyeri tumit',
  'kulit kering': 'kulit bersisik',
  'kulit mengelupas': 'kulit bersisik',
  psoriasis: 'kulit bersisik',
  'kulit pecah': 'kulit bersisik',
  bisul: 'bisul',
  furunkel: 'bisul',
  'abses kulit': 'bisul',
  'benjolan bernanah': 'bisul',
  kurap: 'kurap',
  tinea: 'kurap',
  'panu merah': 'kurap',
  'jamur kulit': 'kurap',
  jerawat: 'jerawat',
  acne: 'jerawat',
  beruntus: 'jerawat',
  'jerawat meradang': 'jerawat',
  kutil: 'kutil',
  veruka: 'kutil',
  'daging tumbuh': 'kutil',
  'rambut rontok': 'rambut rontok',
  'rambut tipis': 'rambut rontok',
  alopesia: 'rambut rontok',
  botak: 'rambut rontok',
  'benjolan payudara': 'benjolan payudara',
  'benjolan di dada': 'benjolan payudara',
  'massa mammae': 'benjolan payudara',
  'payudara bengkak': 'payudara bengkak nyeri',
  'pd nyeri': 'payudara bengkak nyeri',
  mastitis: 'payudara bengkak nyeri',
  'payudara keras': 'payudara bengkak nyeri',
  'punggung atas pegal': 'nyeri punggung atas',
  'belikat sakit': 'nyeri punggung atas',
  'pegal bahu': 'nyeri punggung atas',
  'nyeri belikat': 'nyeri punggung atas',
  'kram kaki': 'kram otot kaki',
  'kram betis': 'kram otot kaki',
  'otot kaki kejang': 'kram otot kaki',
  'betis kram': 'kram otot kaki',
  cegukan: 'cegukan',
  singultus: 'cegukan',
  sendawa: 'sering bersendawa',
  'sering sendawa': 'sering bersendawa',
  'bersendawa terus': 'sering bersendawa',
  'lidah pahit': 'lidah pahit',
  'mulut pahit': 'lidah pahit',
  'rasa hambar': 'lidah pahit',
  disgeusia: 'lidah pahit',
  'mudah lebam': 'mudah memar',
  lebam: 'mudah memar',
  memar: 'mudah memar',
  'biru-biru': 'mudah memar',
  pucat: 'pucat',
  'muka pucat': 'pucat',
  'bibir pucat': 'pucat',
  pallor: 'pucat',
  anemia: 'pucat',
  bintitan: 'mata bintitan',
  'mata bengkak': 'mata bintitan',
  hordeolum: 'mata bintitan',
  belekan: 'mata belekan',
  'mata belekan': 'mata belekan',
  'kotoran mata': 'mata belekan',
  'mata bernanah': 'mata belekan',
  mengi: 'napas berbunyi',
  wheezing: 'napas berbunyi',
  'napas ngik-ngik': 'napas berbunyi',
  'napas bunyi': 'napas berbunyi',
  'keringat malam': 'keringat malam',
  'berkeringat malam': 'keringat malam',
  'night sweats': 'keringat malam',
  pelupa: 'mudah lupa',
  'sering lupa': 'mudah lupa',
  'daya ingat turun': 'mudah lupa',
  pikun: 'mudah lupa',
  cemas: 'gelisah cemas',
  gelisah: 'gelisah cemas',
  khawatir: 'gelisah cemas',
  anxiety: 'gelisah cemas',
  panik: 'gelisah cemas',
  sedih: 'perasaan sedih',
  murung: 'perasaan sedih',
  depresi: 'perasaan sedih',
  'tidak semangat': 'perasaan sedih',
  gemetar: 'tangan gemetar',
  tremor: 'tangan gemetar',
  'tangan goyang': 'tangan gemetar',
  menggigil: 'menggigil',
  rigor: 'menggigil',
  kedinginan: 'menggigil',
  'benjolan leher': 'benjolan leher ketiak',
  'benjolan ketiak': 'benjolan leher ketiak',
  'kelenjar bengkak': 'benjolan leher ketiak',
  limfadenopati: 'benjolan leher ketiak',
  'tidak bisa cium bau': 'anosmia',
  anosmia: 'anosmia',
  'penciuman hilang': 'anosmia',
  'hidung tidak bisa bau': 'anosmia',
  'nyeri wajah': 'nyeri wajah',
  'wajah sakit': 'nyeri wajah',
  neuralgia: 'nyeri wajah',
  trigeminal: 'nyeri wajah',
  'telinga penuh': 'telinga terasa penuh',
  'telinga tersumbat': 'telinga terasa penuh',
  'kuping budeg': 'telinga terasa penuh',
  wasir: 'benjolan anus',
  ambeien: 'benjolan anus',
  hemoroid: 'benjolan anus',
  'benjolan dubur': 'benjolan anus',
  'kencing darah': 'kencing berdarah',
  hematuria: 'kencing berdarah',
  'pipis darah': 'kencing berdarah',
  'kencing pasir': 'kencing berpasir',
  'kencing keruh': 'kencing berpasir',
  'batu ginjal': 'kencing berpasir',
  'anyang-anyangan': 'anyang-anyangan',
  'kencing tidak tuntas': 'anyang-anyangan',
  sistitis: 'anyang-anyangan',
  'gatal kemaluan': 'gatal kemaluan',
  'gatal selangkangan': 'gatal kemaluan',
  'gatal alat kelamin': 'gatal kemaluan',
  dispareunia: 'nyeri berhubungan',
  'sakit berhubungan': 'nyeri berhubungan',
  'nyeri koitus': 'nyeri berhubungan',
  lepuhan: 'lepuhan berair',
  'kulit melepuh': 'lepuhan berair',
  cacar: 'lepuhan berair',
  herpes: 'lepuhan berair',
  'gigitan serangga': 'luka gigitan',
  'digigit nyamuk': 'luka gigitan',
  'bentol gigitan': 'luka gigitan',
  'tangan dingin': 'akral dingin',
  'kaki dingin': 'akral dingin',
  'akral dingin': 'akral dingin',
  'bau badan': 'bau badan',
  bromhidrosis: 'bau badan',
  'keringat bau': 'bau badan',
  'kuku rapuh': 'kuku rapuh',
  'kuku kuning': 'kuku rapuh',
  'jamur kuku': 'kuku rapuh',
  onikomikosis: 'kuku rapuh',
  'mengganjal di leher': 'rasa mengganjal leher',
  globus: 'rasa mengganjal leher',
  'tenggorokan mengganjal': 'rasa mengganjal leher',
  'seperti ada yang tersangkut': 'rasa mengganjal leher',
}

/**
 * Expand a raw query string using symptom aliases.
 * Checks both multi-word and single-word aliases against the lowercased query.
 * Returns the original query with clinical terms appended.
 */
export function expandQueryWithAliases(rawQuery: string): string {
  const lower = rawQuery.toLowerCase()
  const expansions = new Set<string>()

  for (const [alias, clinical] of Object.entries(SYMPTOM_ALIASES)) {
    if (lower.includes(alias)) {
      // Add the clinical term (split multi-word targets)
      expansions.add(clinical)
    }
  }

  if (expansions.size === 0) return rawQuery
  return `${rawQuery} ${[...expansions].join(' ')}`
}
