export const Route = Object.freeze({
  SOLO: 'SOLO',
  DECOMPOSE: 'DECOMPOSE',
});

export const WorkerClass = Object.freeze({
  ROOT: 'ROOT',
  ECONOMY: 'ECONOMY',
  STRONG: 'STRONG',
});

export const TaskState = Object.freeze({
  PENDING: 'PENDING',
  READY: 'READY',
  RUNNING: 'RUNNING',
  VERIFYING: 'VERIFYING',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  BLOCKED: 'BLOCKED',
  CANCELLED: 'CANCELLED',
});

export const FailureClass = Object.freeze({
  SPEC_ERROR: 'SPEC_ERROR',
  CAPABILITY_MISMATCH: 'CAPABILITY_MISMATCH',
  TEST_FAILURE: 'TEST_FAILURE',
  SCOPE_VIOLATION: 'SCOPE_VIOLATION',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',
  ENVIRONMENT_FAILURE: 'ENVIRONMENT_FAILURE',
  SECURITY_RISK: 'SECURITY_RISK',
  BLOCKED_REQUIREMENT: 'BLOCKED_REQUIREMENT',
  BUDGET_EXHAUSTED: 'BUDGET_EXHAUSTED',
  ADAPTER_UNAVAILABLE: 'ADAPTER_UNAVAILABLE',
});

export const AuditVerdict = Object.freeze({
  SHIP: 'SHIP',
  FIX_FIRST: 'FIX_FIRST',
  RETHINK: 'RETHINK',
});
