import type { ModeId } from "./drafts";

// Sentrapedia — Templat Klinis Indonesia v1 (Chief, 2026-10-09): the 18 modes in clinical-workflow order and six
// categories, each with a structure the clinician can preview and insert into the composer. Content only: local drafts
// and MIRA keep their own output. The four modes the pack marked for audit map to workup, icd10, monitoring and refer.
export const templateCategories = ["Dokumentasi klinis", "Diagnosis dan evaluasi", "Komunikasi dan tindak lanjut", "Koordinasi pelayanan", "Evidence-based practice", "Administrasi klinis"] as const;
export const missingField = "Belum tersedia — lengkapi dan verifikasi oleh klinisi";
export interface ClinicalTemplate { mode: ModeId; category: typeof templateCategories[number]; name: string; sections: [string, string[]][]; rule: string }
export const clinicalTemplates: ClinicalTemplate[] = [
  { mode: "hpi", category: "Dokumentasi klinis", name: "Anamnesis Terstruktur — HPI Komprehensif", sections: [["Identitas dokumentasi", ["Tanggal dan waktu anamnesis", "Sumber informasi dan reliabilitas anamnesis"]], ["Keluhan dan kronologi", ["Keluhan utama (kata-kata pasien)", "Awitan, durasi, dan perjalanan keluhan", "Lokasi, penjalaran, karakter, dan intensitas", "Frekuensi, pola, serta faktor pencetus/peringan", "Gejala penyerta dan gejala yang disangkal (pertinent negatives)"]], ["Konteks relevan", ["Riwayat penyakit dan tindakan terdahulu", "Obat yang digunakan dan riwayat alergi", "Riwayat keluarga, sosial, dan faktor risiko yang relevan"]], ["Klarifikasi", ["Pertanyaan lanjutan yang belum terjawab", "Ringkasan kronologis berdasarkan keterangan yang tersedia"]]], rule: "Jangan menyimpulkan diagnosis dari anamnesis; pisahkan pernyataan pasien dan interpretasi klinisi." },
  { mode: "clinic", category: "Dokumentasi klinis", name: "Catatan Kunjungan — SOAP Standar Indonesia", sections: [["Identitas pertemuan", ["Tanggal/waktu dan jenis layanan", "Tujuan kunjungan"]], ["S — Subjective", ["Keluhan utama dan HPI", "Riwayat penyakit yang relevan", "Obat, alergi, dan faktor risiko terkait"]], ["O — Objective", ["Tanda vital (angka, satuan, waktu bila tersedia)", "Pemeriksaan fisik yang benar-benar dilakukan", "Hasil pemeriksaan penunjang dengan tanggal dan satuan"]], ["A — Assessment", ["Daftar masalah dan diagnosis yang dinyatakan klinisi", "Pertimbangan diagnosis banding yang dinyatakan klinisi", "Tingkat kepastian dan informasi yang masih belum tersedia"]], ["P — Plan", ["Pemeriksaan/rujukan yang disepakati", "Terapi atau tindakan yang diresepkan/dilakukan klinisi", "Edukasi, informed discussion, dan kewaspadaan yang disampaikan", "Rencana pemantauan dan kontrol ulang"]], ["Pengesahan", ["Nama/peran klinisi penelaah", "Status verifikasi catatan"]]], rule: "Pertahankan batas S/O/A/P. Jangan memindahkan keluhan pasien menjadi hasil pemeriksaan objektif." },
  { mode: "ddx", category: "Dokumentasi klinis", name: "Lembar Kerja Diagnosis Banding — DDx", sections: [["Perumusan masalah", ["Masalah klinis yang dinilai", "Temuan positif utama", "Temuan negatif bermakna", "Faktor risiko/konteks relevan"]], ["Daftar diagnosis kandidat dari klinisi", ["Kandidat 1: nama diagnosis yang dinyatakan klinisi", "Kandidat 1: bukti mendukung", "Kandidat 1: bukti tidak mendukung atau belum tersedia", "Kandidat 2 dan seterusnya: gunakan struktur sama"]], ["Pembedaan dan tindak lanjut", ["Pemeriksaan pembeda yang dipertimbangkan klinisi", "Tanda bahaya yang diidentifikasi klinisi", "Data tambahan yang harus diperoleh", "Rencana dan penanggung jawab tindak lanjut"]]], rule: "Jangan menghasilkan kandidat DDx baru atau memberi probabilitas diagnosis tanpa masukan klinisi." },
  { mode: "ap", category: "Dokumentasi klinis", name: "Asesmen dan Rencana — Berbasis Daftar Masalah", sections: [["Ringkasan asesmen", ["Konteks pertemuan", "Data kunci dan penilaian yang dinyatakan klinisi"]], ["Masalah 1 — ulangi per masalah", ["Masalah/diagnosis yang dinyatakan klinisi", "Dasar asesmen dan status masalah", "Pemeriksaan atau investigasi yang direncanakan", "Penatalaksanaan medis/nonmedis yang sudah ditetapkan", "Konseling, monitoring, dan kriteria evaluasi", "Jadwal tindak lanjut dan penanggung jawab"]], ["Koordinasi", ["Kebutuhan rujukan/konsultasi", "Masalah terbuka untuk ditinjau pada pertemuan berikutnya"]]], rule: "Terapi, dosis, tindakan, dan follow-up harus berasal dari keputusan klinisi, bukan inferensi sistem." },
  { mode: "scribe", category: "Dokumentasi klinis", name: "Catatan Scribe — Transkrip dan Verifikasi Klinis", sections: [["Sumber dokumentasi", ["Sumber/jenis transkrip", "Tanggal dan konteks percakapan", "Status kelengkapan transkrip"]], ["Pemisahan isi", ["Ucapan pasien/pendamping secara verbatim atau ditandai sebagai parafrasa", "Pertanyaan dan arahan klinisi", "Temuan pemeriksaan yang secara eksplisit disebutkan", "Asesmen dan rencana yang secara eksplisit dinyatakan klinisi"]], ["Tinjauan mutu", ["Bagian tidak jelas/tidak terdengar", "Kontradiksi dan atribusi pembicara yang belum pasti", "Informasi yang belum terkonfirmasi"]], ["Pengesahan", ["Ringkasan untuk pemeriksaan klinisi", "Status persetujuan klinisi sebelum digunakan"]]], rule: "Jangan mengubah perkataan ambigu menjadi fakta klinis, diagnosis, tindakan, atau pemberian obat." },
  { mode: "workup", category: "Diagnosis dan evaluasi", name: "Telaah Pemeriksaan Penunjang — Hasil dan Tindak Lanjut", sections: [["Permintaan dan indikasi", ["Jenis pemeriksaan", "Indikasi klinis yang dinyatakan", "Tanggal permintaan/pelaksanaan", "Status pemeriksaan (direncanakan/dilakukan/menunggu hasil)"]], ["Hasil terverifikasi", ["Parameter/temuan", "Nilai, satuan, dan rentang rujukan sesuai sumber", "Tanggal/jam hasil serta sumber laporan", "Temuan abnormal yang diberi penanda oleh laporan asli"]], ["Telaah klinisi", ["Interpretasi yang dinyatakan klinisi", "Kesesuaian dengan konteks klinis", "Hasil yang perlu dikonfirmasi atau pemeriksaan ulang"]], ["Tindak lanjut", ["Tindakan/komunikasi hasil yang telah ditetapkan", "Penanggung jawab dan target waktu follow-up"]]], rule: "Jangan mengisi hasil laboratorium/imaging, rentang rujukan, atau tingkat kegawatan tanpa data sumber." },
  { mode: "icd10", category: "Diagnosis dan evaluasi", name: "Verifikasi Pengodean Diagnosis — ICD-10", sections: [["Konteks pengodean", ["Jenis layanan dan tujuan pengodean", "Diagnosis naratif sesuai dokumentasi klinisi", "Diagnosis utama atau sekunder"]], ["Kode yang ditelaah", ["Kode ICD-10 yang diajukan oleh petugas/klinisi", "Deskripsi resmi kode dari sumber yang diperiksa", "Versi/sistem klasifikasi dan sumber referensi", "Dukungan dokumentasi dan status kepastian diagnosis"]], ["Uji konsistensi", ["Perbedaan antara diagnosis tertulis dan deskripsi kode", "Informasi spesifisitas yang belum dicatat", "Kebutuhan klarifikasi kepada klinisi"]], ["Finalisasi", ["Kode final setelah verifikasi", "Nama peninjau dan tanggal pemeriksaan"]]], rule: "Hindari penetapan kode otomatis dari gejala; kode dan deskripsinya harus diverifikasi terhadap sumber resmi yang relevan." },
  { mode: "chronic", category: "Diagnosis dan evaluasi", name: "Tinjauan Penyakit Kronis — Longitudinal", sections: [["Konteks longitudinal", ["Kondisi kronis aktif menurut klinisi", "Tanggal penilaian terakhir dan alasan kontrol"]], ["Perubahan sejak kunjungan sebelumnya", ["Perubahan keluhan/gejala", "Kejadian akut, rawat inap, atau efek samping yang dilaporkan", "Perubahan aktivitas, fungsi, dan kepatuhan terapi"]], ["Evaluasi berkala", ["Obat saat ini dan perubahan yang tercatat", "Parameter pemantauan dan hasil bertanggal", "Target kendali yang ditetapkan klinisi", "Komorbiditas dan faktor risiko yang relevan"]], ["Rencana bersama", ["Masalah prioritas dan keputusan klinisi", "Edukasi serta tujuan perawatan yang disepakati", "Pemeriksaan dan tindak lanjut berikutnya"]]], rule: "Tren klinis hanya boleh dibuat jika tersedia beberapa pengukuran bertanggal yang sebanding." },
  { mode: "monitoring", category: "Diagnosis dan evaluasi", name: "Pemantauan Klinis — Parameter dan Eskalasi", sections: [["Rencana pemantauan", ["Kondisi/masalah yang dipantau", "Parameter dan metode pengukuran", "Frekuensi dan durasi pemantauan", "Target atau ambang eskalasi yang ditetapkan klinisi"]], ["Hasil pemantauan", ["Waktu tiap observasi", "Hasil terukur beserta satuan dan sumber", "Perbandingan dengan data sebelumnya jika tersedia", "Keluhan dan kejadian selama pemantauan"]], ["Tindakan dan eskalasi", ["Penilaian klinisi atas perubahan", "Tindakan yang telah dilakukan atau diinstruksikan", "Penerima eskalasi, waktu, dan respons"]], ["Penutupan", ["Status pemantauan saat ini", "Rencana evaluasi berikutnya"]]], rule: "Jangan membuat nilai target, alarm, atau menyimpulkan perburukan tanpa data dan kriteria dari klinisi." },
  { mode: "avs", category: "Komunikasi dan tindak lanjut", name: "Ringkasan Setelah Kunjungan — Bahasa Pasien", sections: [["Ringkasan hari ini", ["Alasan datang dan pokok pembahasan", "Kesimpulan yang sudah dijelaskan klinisi dalam bahasa sederhana"]], ["Apa yang perlu dilakukan", ["Pengobatan/tindakan yang benar-benar disepakati", "Cara penggunaan obat sesuai instruksi yang terdokumentasi", "Pemeriksaan atau rujukan yang direncanakan"]], ["Tindak lanjut dan keselamatan", ["Jadwal/cara kontrol yang disepakati", "Tanda bahaya dan kapan mencari pertolongan sesuai instruksi klinisi", "Kontak fasilitas atau jalur bantuan yang telah dikonfirmasi"]], ["Konfirmasi", ["Hal yang perlu ditanyakan pasien", "Status peninjauan akhir oleh klinisi"]]], rule: "Dokumen ditujukan kepada pasien: gunakan istilah mudah; jangan menampilkan placeholder yang belum diverifikasi saat diberikan." },
  { mode: "education", category: "Komunikasi dan tindak lanjut", name: "Lembar Edukasi Pasien — Terstruktur", sections: [["Topik edukasi", ["Kondisi atau topik yang telah disampaikan klinisi", "Tujuan edukasi yang sesuai kebutuhan pasien"]], ["Pesan utama", ["Penjelasan singkat sesuai informasi terverifikasi", "Anjuran perawatan mandiri yang disetujui klinisi", "Instruksi obat/tindakan yang sudah ditetapkan", "Hal yang perlu dihindari sesuai instruksi klinisi"]], ["Kapan kembali", ["Tanda bahaya sesuai instruksi klinisi", "Rencana kontrol dan tindak lanjut"]], ["Konfirmasi pemahaman", ["Pertanyaan pasien", "Metode teach-back/ulang pemahaman jika dilakukan", "Materi dan bahasa yang digunakan"]]], rule: "Jangan menyisipkan saran pengobatan umum seolah telah diberikan klinisi; semua arahan klinis wajib ditinjau." },
  { mode: "telephone", category: "Komunikasi dan tindak lanjut", name: "Catatan Konsultasi Telepon — Kontak Klinis", sections: [["Rincian kontak", ["Tanggal/jam dan durasi bila dicatat", "Jenis saluran komunikasi", "Identitas/peran penelepon dan hubungan dengan pasien", "Cara verifikasi identitas yang dilakukan"]], ["Isi konsultasi", ["Alasan menghubungi", "Keluhan dan temuan yang dilaporkan penelepon", "Hal yang tidak dapat dinilai melalui telepon", "Pertanyaan dan jawaban yang penting"]], ["Keputusan klinis", ["Arahan yang benar-benar diberikan klinisi", "Anjuran pemeriksaan langsung/rujukan jika diberikan", "Tanda bahaya yang dikomunikasikan", "Rencana kontak atau kontrol ulang"]], ["Penutupan", ["Persetujuan/pemahaman penelepon yang terdokumentasi", "Identitas klinisi yang memberikan arahan"]]], rule: "Jangan mengklaim pemeriksaan fisik langsung dilakukan dalam kontak telepon." },
  { mode: "tasks", category: "Komunikasi dan tindak lanjut", name: "Daftar Tindak Lanjut Kunjungan — Checklist", sections: [["Konteks tugas", ["Pertemuan/masalah yang mendasari tugas", "Tanggal penyusunan daftar"]], ["Tugas — duplikasi untuk tiap item", ["Deskripsi tugas yang sudah ditetapkan", "Penanggung jawab", "Batas waktu atau waktu peninjauan", "Status: belum mulai / berlangsung / selesai / tertunda", "Bukti penyelesaian atau alasan tertunda"]], ["Koordinasi dan penutupan", ["Tugas yang menunggu hasil atau konfirmasi", "Penerima hasil dan tindak lanjut yang diperlukan", "Tanggal evaluasi ulang daftar tugas"]]], rule: "Checklist hanya memuat pekerjaan yang memang diminta atau disetujui; status selesai memerlukan bukti." },
  { mode: "referral", category: "Koordinasi pelayanan", name: "Surat Rujukan Medis — Antarfasilitas", sections: [["Identitas dan tujuan surat", ["Tanggal surat dan fasilitas pengirim", "Fasilitas/poli/dokter tujuan", "Identitas pasien sesuai sistem resmi (jangan simpan PHI pada demo browser)", "Prioritas rujukan sebagaimana dinyatakan klinisi"]], ["Isi rujukan", ["Alasan rujukan dan pertanyaan untuk penerima", "Keluhan, riwayat, dan kronologi penting", "Temuan pemeriksaan fisik yang tersedia", "Pemeriksaan penunjang beserta tanggal/hasil", "Asesmen/diagnosis yang dinyatakan klinisi", "Tindakan, pengobatan, dan respons sebelumnya", "Obat aktif dan alergi yang tercatat"]], ["Koordinasi", ["Tindakan atau evaluasi yang dimohon", "Lampiran yang benar-benar tersedia", "Informasi komunikasi dan tindak lanjut"]], ["Pengesahan", ["Nama, jabatan, dan tanda tangan/otorisasi klinisi", "Tanggal verifikasi final"]]], rule: "Isi surat hanya data terverifikasi; identitas pasien nyata harus dikelola melalui sistem aman, bukan localStorage demo." },
  { mode: "refer", category: "Koordinasi pelayanan", name: "Telaah Rujukan — Kelayakan Dokumen dan Koordinasi", sections: [["Informasi permintaan", ["Asal dan tujuan rujukan", "Pertanyaan/tujuan klinis rujukan", "Tingkat prioritas yang disebut pengirim", "Waktu dan status penerimaan"]], ["Kelengkapan informasi", ["Ringkasan masalah klinis dan alasan rujukan", "Riwayat serta pemeriksaan yang disertakan", "Hasil penunjang, pengobatan, dan respons yang disertakan", "Dokumen/lampiran yang belum tersedia"]], ["Telaah dan tindak lanjut", ["Kebutuhan klarifikasi kepada fasilitas pengirim", "Penilaian kesesuaian administratif menurut kriteria yang disediakan", "Penilaian klinis dan keputusan dari petugas yang berwenang", "Rencana koordinasi/eskalasi dan pihak penanggung jawab"]], ["Hasil akhir", ["Status rujukan dan alasan yang terdokumentasi", "Tanggal dan penanggung jawab keputusan"]]], rule: "Jangan memutuskan menerima/menolak rujukan secara otomatis berdasarkan data parsial." },
  { mode: "handoff", category: "Koordinasi pelayanan", name: "Serah Terima Klinis — SBAR dan Read-back", sections: [["Identitas handoff", ["Waktu/shift dan unit kerja", "Pemberi dan penerima serah terima", "Identifikasi kasus melalui sistem aman"]], ["S — Situation", ["Alasan serah terima dan masalah utama", "Status terbaru serta urgensi yang dinyatakan klinisi"]], ["B — Background", ["Riwayat singkat dan komorbiditas relevan", "Intervensi, obat, alergi, dan pemeriksaan terkini"]], ["A — Assessment", ["Penilaian klinisi atas kondisi dan perubahan", "Masalah aktif, hasil tertunda, serta risiko yang telah diidentifikasi"]], ["R — Recommendation", ["Tindakan berikutnya dan prioritas yang ditetapkan", "Parameter pemantauan dan kapan eskalasi", "Pekerjaan tertunda, penanggung jawab, dan tenggat"]], ["Konfirmasi", ["Read-back atau konfirmasi penerimaan", "Hal yang belum dipahami dan tindak lanjut klarifikasi"]]], rule: "Kritis untuk kesinambungan pelayanan: tindakan dan urgensi tidak boleh dikarang dari transkrip tidak lengkap." },
  { mode: "question", category: "Evidence-based practice", name: "Pertanyaan Klinis — PICO dan Telaah Bukti", sections: [["Rumusan pertanyaan", ["Masalah dan konteks layanan", "Jenis pertanyaan (terapi/diagnostik/prognosis/etiologi/dll.)"]], ["PICO", ["P — Population/Patient/Problem", "I — Intervention/Index Test/Exposure", "C — Comparator (bila relevan)", "O — Outcome klinis yang ingin dinilai"]], ["Strategi verifikasi", ["Pertanyaan klinis dalam satu kalimat", "Kata kunci dan sinonim pencarian", "Jenis studi/pedoman yang perlu diverifikasi", "Sumber/pedoman yang benar-benar diperiksa (judul, tahun, tautan)"]], ["Sintesis untuk klinisi", ["Temuan literatur yang telah diverifikasi", "Keterbatasan/ketidakpastian bukti", "Relevansi untuk pasien dan keputusan yang masih perlu ditelaah"]]], rule: "Jangan mengarang studi, rekomendasi pedoman, nomor DOI, atau tingkat kepastian bukti." },
  { mode: "authorization", category: "Administrasi klinis", name: "Permohonan Persetujuan Penjaminan — Justifikasi Medis", sections: [["Data permohonan", ["Penjamin/payer dan jenis manfaat", "Tindakan/layanan/obat yang dimohon", "Fasilitas/pemberi pelayanan pemohon", "Nomor/identifikasi permohonan dalam sistem aman"]], ["Justifikasi medis", ["Diagnosis yang didokumentasikan dan kode yang diverifikasi", "Indikasi serta kebutuhan medis menurut klinisi", "Riwayat terapi/pemeriksaan sebelumnya dan respons nyata", "Alasan opsi sebelumnya tidak memadai bila dinyatakan", "Dokumen penunjang yang benar-benar tersedia"]], ["Administrasi dan keputusan", ["Kriteria penjamin yang telah diperiksa", "Dokumen wajib yang masih kurang", "Status permohonan, korespondensi, dan batas waktu", "Keputusan penjamin jika sudah diterima"]], ["Pengesahan", ["Pernyataan/otorisasi klinisi penanggung jawab", "Tanggal peninjauan akhir"]]], rule: "Catatan ini bukan persetujuan otomatis atau jaminan pembiayaan; keputusan tetap pada penjamin." },
];

export const modeCategories = templateCategories.map((label) => ({ label, modes: clinicalTemplates.filter((item) => item.category === label).map((item) => item.mode) }));

// The structure as the pack writes it: title and review line, then each section in capitals with its fields marked missing.
export function templateText(template: ClinicalTemplate): string {
  return [`${template.name.toUpperCase()}\nDRAF — VERIFIKASI KLINISI DIPERLUKAN`, ...template.sections.map(([heading, fields]) => `${heading.toUpperCase()}\n${fields.map((field) => `- ${field}: ${missingField}`).join("\n")}`)].join("\n\n");
}

// Inserting keeps what is already typed: the structure goes after it.
export function insertTemplate(prompt: string, text: string): string {
  return prompt.trim() ? `${prompt.trimEnd()}\n\n${text}` : text;
}
